/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/app-info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** App Info */
    get: operations["app_info_api_app_info_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/diff": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Diff */
    get: operations["diff_api_diff_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/markdown/content/{content_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Markdown Content */
    get: operations["markdown_content_api_markdown_content__content_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/browser/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Browser Status */
    get: operations["browser_status_api_browser_status_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AppInfo
     * @description Identity of the running backend — a cheap wiring + auth probe.
     */
    AppInfo: {
      /** Name */
      name: string;
      /** Version */
      version: string;
    };
    /**
     * BrowserStatus
     * @description Whether the live browser stack (x11vnc) is reachable on the VM (ADR-0006).
     */
    BrowserStatus: {
      /** Running */
      running: boolean;
    };
    /**
     * DiffHunk
     * @description One contiguous hunk of a file's diff, pre-parsed for the frontend.
     */
    DiffHunk: {
      /** Id */
      id: string;
      /** File Path */
      file_path: string;
      /** Language */
      language: string;
      /** Is Binary */
      is_binary: boolean;
      /** Is Empty */
      is_empty: boolean;
      /** Hunk Header */
      hunk_header: string;
      /** Lines */
      lines: components["schemas"]["HunkLine"][];
    };
    /**
     * DiffResponse
     * @description The working-tree diff of a context, as pre-parsed hunks.
     */
    DiffResponse: {
      /** Context */
      context: string;
      /** Hunks */
      hunks: components["schemas"]["DiffHunk"][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HunkLine
     * @description A single line within a diff hunk. ``old_no``/``new_no`` are null where the
     *     line is absent on that side (added lines have no old number, etc.).
     */
    HunkLine: {
      /**
       * Type
       * @enum {string}
       */
      type: "context" | "add" | "delete";
      /** Old No */
      old_no: number | null;
      /** New No */
      new_no: number | null;
      /** Content */
      content: string;
    };
    /**
     * MarkdownContentResponse
     * @description An ephemeral markdown snapshot (plan text, a sent ``.md`` file).
     */
    MarkdownContentResponse: {
      /** Title */
      title: string;
      /** Content */
      content: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  app_info_api_app_info_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AppInfo"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  diff_api_diff_get: {
    parameters: {
      query?: {
        context?: string | null;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DiffResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  markdown_content_api_markdown_content__content_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        content_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MarkdownContentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  browser_status_api_browser_status_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BrowserStatus"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
